default: &default
  adapter: postgresql

development:
  <<: *default
  database: cfp-dev

test:
  <<: *default
  username: postgres
  password: mysecretpassword
  host: postgres
  database: cfp-test

staging:
  <<: *default
  database: cfp-staging

production:
  <<: *default
  database: cfp-production