default: &default
  adapter: postgresql

development:
  <<: *default
  database: cfp-development

test:
  <<: *default
  host: postgres
  database: cfp-test

production:
  <<: *default
  database: cfp-production
