development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "cfptestgogo@gmail.com"
  password: "opyfetlvpacyiqsz"
  enable_starttls_auto: true
production:
  address: "smtp.mailgun.org"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "cfptestgogo@gmail.com"
  password: "opyfetlvpacyiqsz"
  enable_starttls_auto: true