errbit:
  host: https://errbit.5xruby.dev
  project_key:
  environment: development
notifier:
  email:
    default_subject: "SUBJECTTT"
  slack:
    default_username: "BOT"
    default_subject: "SUBJECTTTTT"
github:
  id:
  secret:
  scope: user:email
twitter:
  id:
  secret:
mailer:
  delivery_method:
  default_reply_to: contact@rubyconf.test
  default_from: "noreply@rubyconf.test"
  bcc_email:
    - contact@rubyconf.test
paper:
  title:
    limit_word: true
    min: 1
    max: 100
  abstract:
    limit_word: true
    min: 10
    max: 601
  bio:
    limit_word: true
    min: 10
    max: 601
notifier:
  email:
    default_subject: "CFP-notification"
  slack:
    default_username: "CFP-notification"
hostname:
  host: "rubyconf.dev"
  port: "80"
